trainer:
  max_epochs: 80
model:
  class_path: E2E.solutions.cgNNfit
  init_args:
    lr_net: 1e-3
    lr_lam: 1e-2
    pretrain_length: 10
    nettype: "2.5d"
    y0iterations: 2
    iterations: 1
    tag: false
    layer: 4
    initial_filters: 16
    netargs:
      activation: "silu"
      residual: "inner"
      norm: "group8"
      change_filters_last: false
    feature_growth:
      - 1.
      - 2
      - 1.5
      - 1.34
      - 1.
      - 1.

data:
  init_args:
    batchsize: 8
