trainer:
  max_epochs: 80
model:
  class_path: E2E.solutions.cgNN2
  init_args:
    ynettype: "2.5d"
    y0iterations: 2
    yiterations: 4
    ytag: true
    ylayer: 4
    yinitial_filters: 16
    ynetargs:
      activation: "silu"
      residual: "inner"
      norm: "group8"
      change_filters_last: false
    yfeature_growth:
      - 1.
      - 2
      - 1.5
      - 1.34
      - 1.
      - 1.
    xinitial_filters: 32
    xlayer: 4
    initial_lambdas:
      - 0.2
    xnetargs:
      activation: "silu"
      residual: "inner"
      norm: "group16"
      change_filters_last: false
    xfeature_growth:
      - 1.
      - 2
      - 1.5
      - 1.34
      - 1.
      - 1.
    pretrain_length: 10
    warmup_length: 1500
    e2e: true
    lr_net: 0.001
data:
  init_args:
    batchsize: 8
